### ISSUE TITLE
Guess & Help Cmd Not Working

### ISSUE THREAD

**Issue by SamArroyos22** [luciengaitskell/Helperbot5000#4]
Ok i fixed the guess command, it had something to do when you nickname the bot it does not recognize it

But the Help command does not work still

**Comment by NorCon13** [comment]
Issue closed. Bot no longer being developed.

**Comment by luciengaitskell** [comment]
@SamArroyos22 
I apologize for this, but we are working on other bots. This was just meant to be a test of the Discord API, and what we can use. You are welcome to push a pull request, if you want. Also, you are welcome to look at our other bots, like [`cards`](https://github.com/helperbot-solutions/python-discord-cards).

Thanks for finding us!

**Comment by SamArroyos22** [comment]
@luciengaitskell Thanks For The Info And Reply, I Managed to Make my own help command and fixed in issue with the guess!

**Comment by luciengaitskell** [comment]
@SamArroyos22 You are welcome to create a pull request, if you want.
